# Generated by Django 4.2.2 on 2023-06-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog/files/%Y/%m/%d/'),
        ),
    ]
